[package]
name = "tauri-specta"
description = "Completely typesafe Tauri commands"
version = "2.0.0-rc.4"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/README.md", "/LICENCE"]
repository = "https://github.com/oscartbeaumont/tauri-specta"
documentation = "https://docs.rs/tauri-specta/latest/tauri-specta"
keywords = ["async", "specta", "rspc", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
javascript = ["specta/typescript", "specta/js_doc"]
typescript = ["specta/typescript", "specta/js_doc"]

[dependencies]
specta = { workspace = true, features = ["functions", "tauri"] }
tauri-specta-macros = { version = "=2.0.0-rc.4", path = "./macros" }
serde = { workspace = true }
serde_json = "1.0.107"
tauri = { workspace = true }
thiserror = "1.0.49"
heck = "0.4.1"
indoc = "2.0.4"

[dev-dependencies]
doc-comment = "0.3.3"

[workspace]
members = [
    "examples/app/src-tauri",
    "examples/custom-plugin/app/src-tauri",
    "examples/custom-plugin/plugin",
    "macros",
]

[workspace.dependencies]
specta = { git = "https://github.com/oscartbeaumont/specta", rev = "673e3f55d246cd90e70c706ba4ca7f5818e99ba9" }
serde = "1.0.188"
tauri = "2.0.0-alpha"
tauri-build = "2.0.0-alpha"
